In [ ]:
pip install numpy


In [ ]:
import numpy as np
arr_1d=np.array([1,2,3])
print(arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr_3d)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
2
3


In [ ]:
z=np.zeros((2,3))
print(z)
o=np.ones((3,3))
print(o)
random_arr=np.random.random((2,2))
print(random_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.8247022  0.40640479]
 [0.78125956 0.52729716]]


In [ ]:
identity=np.eye(3)
print(identity)
range_arr=np.arange(0,10,2)
print(range_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("Number of dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
Data Type: int64
Number of dimensions: 2


In [20]:
GH1=np.array([22,25,20])
GH2=np.array([24,26,23])
temp_data=np.array([GH1,GH2])
print("Temperature Data(temp_data):")
print(temp_data)

print("Array Properties:")
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data Type:",temp_data.dtype)
print("Number of Dimensions:",temp_data.ndim)

GH3=np.array([21,23,22])
updated_temp_data=np.vstack([temp_data,GH3])
print("Updated Temperature Data(updated_temp_data):")
print(updated_temp_data)

sensor_error_flags=np.zeros((2,3),dtype=int)
greenhouse_identity=np.identity(3,dtype=int)
print("Sensor Error Flags(sensor_error_flags):")
print(sensor_error_flags)

print("Greenhouse Identity Matrix(greenhouse_identity):")
print(greenhouse_identity)


Temperature Data(temp_data):
[[22 25 20]
 [24 26 23]]
Array Properties:
Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2
Updated Temperature Data(updated_temp_data):
[[22 25 20]
 [24 26 23]
 [21 23 22]]
Sensor Error Flags(sensor_error_flags):
[[0 0 0]
 [0 0 0]]
Greenhouse Identity Matrix(greenhouse_identity):
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [22]:
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,-1])
print(arr[:,1:])

20
60
[[20 30]
 [50 60]]


In [26]:
Apples=np.array([50,60,55,70,65,80,90])
Oranges=np.array([40,45,50,60,55,70,75])
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)
print("Apples shipped on wednesday:",shipments[0,2])
print("Oranges shipped on Sunday",shipments[1,6])
print("Weekday Shipments (Mon–Fri):",shipments[:, 0:5])
print("Weekend Shipments (Sat–Sun):",shipments[:, 5:7])
print("Apples Shipments (Wed–Sat):",shipments[0, 2:6])
shipments[0,5]=100
print("Updated Shipments after modifying Saturday Apples to 100:")
print(shipments)


[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
Apples shipped on wednesday: 55
Oranges shipped on Sunday 75
Weekday Shipments (Mon–Fri): [[50 60 55 70 65]
 [40 45 50 60 55]]
Weekend Shipments (Sat–Sun): [[80 90]
 [70 75]]
Apples Shipments (Wed–Sat): [55 70 65 80]
Updated Shipments after modifying Saturday Apples to 100:
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [28]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(b-a)
print(a*b)
print(a*2)
res=np.dot(a,b)
print(res)

[5 7 9]
[3 3 3]
[ 4 10 18]
[2 4 6]
32


In [35]:
a=np.array([1,2,3]) #broadcasting
b=2
print(a+b)
arr=np.array([1,2,3])
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.add(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.min(a))
print(np.max(a))
print(np.round(a))
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.std(a))
print(np.var(a))


[3 4 5]
[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[3 4 5]
[1 4 9]
[1 0 1]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
1
3
[1 2 3]
[1. 2. 3.]
[1. 2. 3.]
[1. 2. 3.]
0.816496580927726
0.6666666666666666


In [36]:
import numpy as np
Farm_A=np.array([
    [10,12,11],
    [9,11,10],
    [12,13,14],
    [8,7,9]
])
Farm_B=np.array([
    [20,19,21],
    [18,20,19],
    [22,23,21],
    [17,18,16]
])
Farm_C=np.array([
    [15,16,14],
    [14,13,12],
    [16,17,18],
    [12,11,13]
])
# STEP 2: Stack into 3D array
production_all=np.stack([Farm_A,Farm_B,Farm_C])
print("Production Data (3 farms × 4 panels × 3 hours):")
print(production_all)
# STEP 3: Array Attributes
print("Shape:",production_all.shape)
print("Size:",production_all.size)
print("Data Type:",production_all.dtype)
print("Dimensions:",production_all.ndim)
# STEP 4: Per-Farm Totals and Statistics
total_per_farm=np.sum(production_all,axis=(1,2))
mean_per_farm=np.mean(production_all,axis=(1,2))
std_per_farm=np.std(production_all,axis=(1,2))
var_per_farm=np.var(production_all,axis=(1,2))
print("Total energy per farm:",total_per_farm)
print("Mean per farm:",mean_per_farm)
print("Std per farm:",std_per_farm)
print("Variance per farm:",var_per_farm)
# STEP 5: Weighted per panel using dot product
hour_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.array([
    np.dot(farm,hour_weights) for farm in production_all
])
print("Weighted energy per panel (per farm):")
print(weighted_per_panel)
# STEP 6: Broadcasting adjustment (+0.5 to Farm B)
production_all[1]= 0.5
print("After calibration offset (+0.5) to Farm B:")
print(production_all[1])
# STEP 7: Normalization (Z-score per farm)
norm_data = (production_all - mean_per_farm[:, None, None])/std_per_farm[:, None, None]
print("Normalized (Z-score) data shape:", norm_data.shape)
# STEP 8: Apply Various UFuncs
exp_data=np.exp(norm_data)
expm1_data = np.expm1(norm_data)
safe_norm = np.abs(norm_data) + 1e-5
log_data = np.log(safe_norm)
log10_data = np.log10(safe_norm)
log2_data = np.log2(safe_norm)
sin_data = np.sin(norm_data)
cos_data = np.cos(norm_data)
tan_data = np.tan(norm_data)
arcsin_data = np.arcsin(np.clip(sin_data, -1, 1))
arccos_data = np.arccos(np.clip(cos_data, -1, 1))
arctan_data = np.arctan(norm_data)
degrees_data = np.degrees(arctan_data)
radians_data = np.radians(degrees_data)
round_data = np.round(norm_data)
floor_data = np.floor(norm_data)
ceil_data = np.ceil(norm_data)
trunc_data = np.trunc(norm_data)
# STEP 9: Comparison & Logical Masks
high_output = production_all > 20
even_hours_mask = np.array([False, True, False])
even_hours_mask_3d = np.tile(even_hours_mask, (3, 4, 1))
and_mask = np.logical_and(high_output, even_hours_mask_3d)
or_mask = np.logical_or(high_output, even_hours_mask_3d)
not_mask = np.logical_not(high_output)
xor_mask = np.logical_xor(high_output, even_hours_mask_3d)
greater_equal_mask = np.greater_equal(production_all, 20)
less_mask = np.less(production_all, 15)
# STEP 10: Bitwise Operations
alerts = np.array([
    [[1, 0, 1],
     [0, 0, 1],
     [1, 1, 0],
     [0, 1, 0]]
] * 3)
bit_and = np.bitwise_and(alerts, (production_all > 18))
bit_or = np.bitwise_or(alerts, (production_all > 18))
bit_not = np.invert(alerts.astype(bool))
# STEP 11: Arithmetic UFuncs
add_data = np.add(production_all, 2)
sub_data = np.subtract(production_all, 5)
mul_data = np.multiply(production_all, 1.2)
div_data = np.divide(production_all, 2)
pow_data = np.power(production_all, 2)
mod_data = np.mod(production_all, 5)
# STEP 12: Aggregations over UFuncs
exp_sum = np.sum(np.exp(norm_data))
sin_mean = np.mean(np.sin(norm_data))
print("Sum of exp(normalized data):", exp_sum)
print("Mean of sin(normalized data):", sin_mean)
# STEP 13: Broadcast-based Summary
panel_totals_per_farm = np.sum(production_all, axis=2)  # (3,4)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("Panel totals per farm (sum across hours):")
print(panel_totals_per_farm)
print("Needs maintenance (panel total < 40):", needs_maintenance)
# STEP 14: Final KPIs
overall_total = np.sum(production_all)
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
average_per_panel = np.mean(production_all, axis=(0, 2))

print("Overall Total Energy Produced:", overall_total)
print("Peak Value:", peak_value)
print("Peak Occurred at Farm, Panel, Hour:", peak_index)
print("Average per panel across all farms:", average_per_panel)


Production Data (3 farms × 4 panels × 3 hours):
[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 12]
  [16 17 18]
  [12 11 13]]]
Shape: (3, 4, 3)
Size: 36
Data Type: int64
Dimensions: 3
Total energy per farm: [126 234 171]
Mean per farm: [10.5  19.5  14.25]
Std per farm: [1.97905701 1.97905701 2.086664  ]
Variance per farm: [3.91666667 3.91666667 4.35416667]
Weighted energy per panel (per farm):
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   29.   38.5  26.75]]
After calibration offset (+0.5) to Farm B:
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Normalized (Z-score) data shape: (3, 4, 3)
Sum of exp(normalized data): 38.77702845913089
Mean of sin(normalized data): 0.1288321198082658
Panel totals per farm (sum across hours):
[[33 30 39 24]
 [ 0  0  0  0]
 [45 39 51 36]]
Needs maintenance (panel total < 40): [ True  True  True]
Overall Total Energy Produced: 297
Peak Value: 18
Peak Occurred at Farm, 

In [37]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [39]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [40]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
a=np.array([10,20,30,40])
indices=[0,2]
print(a[indices])

[4 5]
[10 30]


In [41]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)

[10  2  3]


In [44]:
import numpy as np
arr1=np.arange(10,51)
print("1D Array (10–50):\n",arr1)
rand_arr=np.random.rand(3,3)
print("\n3x3 Random Array:\n", rand_arr)
# Array Attributes
print("\nArray Attributes:")
print("Shape:", rand_arr.shape)
print("Size:", rand_arr.size)
print("Data type:", rand_arr.dtype)
#Basic Operations
arr_plus5=arr1 + 5
print("\nArray after adding 5:\n",arr_plus5)
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[2,2,2],[3,3,3]])
elementwise_mult=A*B
print("\nElement-wise multiplication:\n",elementwise_mult)
#Indexing and Slicing
arr5x5=np.arange(1,26).reshape(5,5)
print("\n5x5 Array:\n",arr5x5)
print("\nFirst row:",arr5x5[0])
print("Last column:",arr5x5[:,-1])
print("Subarray (first 3 rows & 2 columns):\n",arr5x5[:3,:2])
#Aggregation
rand_ints=np.random.randint(10,100,10)
print("\nRandom Integers:",rand_ints)
print("Max:",np.max(rand_ints))
print("Min:",np.min(rand_ints))
print("Mean:",np.mean(rand_ints))
print("Standard Deviation:",np.std(rand_ints))
# Reshaping
arr_reshaped=np.arange(1,13).reshape(3,4)
print("\nReshaped 3x4 Array:\n",arr_reshaped)
# Broadcasting
matrix_ones=np.ones((3,3))
arr_to_add=np.array([1,2,3])
broadcasted_sum=matrix_ones+arr_to_add
print("\nBroadcasted Addition:\n", broadcasted_sum)
#Filtering
rand_filter= np.random.randint(1,50,10)
div_by_5 = rand_filter[rand_filter % 5==0]
print("\nRandom Integers:",rand_filter)
print("Elements divisible by 5:",div_by_5)
# Matrix Multiplication
mat1=np.array([[2,4],[1,3]])
mat2=np.array([[5,2],[7,6]])
mat_mul = np.dot(mat1, mat2)
print("\nMatrix 1:\n",mat1)
print("Matrix 2:\n",mat2)
print("Matrix Multiplication:\n", mat_mul)
# Advanced Indexing
arr4x4 = np.arange(1,17).reshape(4,4)
print("\n4x4 Array:\n",arr4x4)
rows=np.arange(4)
cols=np.arange(4)
diagonal_elements=arr4x4[rows, cols]
print("Diagonal Elements:",diagonal_elements)


1D Array (10–50):
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

3x3 Random Array:
 [[0.51124857 0.40700732 0.35533753]
 [0.67220239 0.85359377 0.28895592]
 [0.94949397 0.79440693 0.0946293 ]]

Array Attributes:
Shape: (3, 3)
Size: 9
Data type: float64

Array after adding 5:
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]

Element-wise multiplication:
 [[ 2  4  6]
 [12 15 18]]

5x5 Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Subarray (first 3 rows & 2 columns):
 [[ 1  2]
 [ 6  7]
 [11 12]]

Random Integers: [36 93 91 54 54 36 35 82 30 31]
Max: 93
Min: 30
Mean: 54.2
Standard Deviation: 24.0574312843246

Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Broadcasted Addition:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3